import './globals.css';

import Provider from '@/lib/provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: Props) => {
  return (
    <html lang='ja'>
      <body className='p-10'>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
};

export default RootLayout;
